version: '2'

services:
  teamcity:
    image: jetbrains/teamcity-agent
    volumes:
      - ./data/server/datadir:/data/teamcity_server/datadir 
      - ./data/server/logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent
    volumes:
      - ./data/agent:/data/teamcity_agent/conf
    environment:
      SERVER URL: http://teamcity

